# Generated by Django 2.2.4 on 2019-08-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='location',
            name='survivor',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='last_location', to='core.Survivor'),
            preserve_default=False,
        ),
    ]
