# Generated by Django 2.2.4 on 2019-08-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190808_1657'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
