# Generated by Django 2.2.4 on 2019-08-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_survivor_last_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survivor',
            name='last_location',
        ),
    ]
