# Generated by Django 2.2.4 on 2019-08-08 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_survivor_last_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='last_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
