# Generated by Django 2.2.4 on 2019-08-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190808_1958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
