# Generated by Django 2.2.4 on 2019-08-09 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
        ('core', '0011_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='survivor',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.Inventory'),
        ),
    ]
