# Generated by Django 2.2.4 on 2019-08-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_survivor_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
