# Generated by Django 2.2.4 on 2019-08-14 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventories.Inventory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survivor',
            name='last_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
            preserve_default=False,
        ),
    ]
