# Generated by Django 2.2.4 on 2019-08-14 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190814_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.Inventory'),
        ),
        migrations.AlterField(
            model_name='survivor',
            name='last_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
    ]
