# Generated by Django 2.2.4 on 2019-08-14 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190814_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='inventory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventories.Inventory'),
        ),
    ]
