# Generated by Django 2.2.4 on 2019-08-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.PositiveIntegerField(default=0)),
                ('food', models.PositiveIntegerField(default=0)),
                ('medication', models.PositiveIntegerField(default=0)),
                ('ammunition', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
