# Generated by Django 2.2.4 on 2019-08-08 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_survivor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='survivor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_location', to='core.Survivor'),
        ),
    ]
